name: Artifact Example Workflow
run-name: ${{ github.actor }} is running artifact example

on: [push]

env:
  OUTPUT_FILE: output.log
  OUTPUT_NAME: output-log-file

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create a log file
      run: echo "This is a log file." > ${{ env.OUTPUT_FILE }}

    - name: Display the log file content
      run: cat ${{ env.OUTPUT_FILE }}

    - name: Upload log file as artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.OUTPUT_NAME }}
        path: ${{ env.OUTPUT_FILE }}

  download:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Download log file artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ env.OUTPUT_NAME }}

    - name: Display the downloaded log file content
      run: cat ${{ env.OUTPUT_FILE }}

